### ISSUE TITLE
parse error:File "parse_changes.cocci", line 379, column 32, charpos = 10837

### ISSUE THREAD

**Issue by taskset** [hvdthong/PatchNetTool#1]
We encountered this problem in testing the preprocessing project.

The commit-list file is：
$ cat /media/B/tsp/git/linux/patches/test
11743c56785c751c087eecdb98713eef796609e0: false
929e134c43c95822663367c47fb211ca272309f7: false
4b42745211af552f170f38a1b97f4a112b5da6b2: false

$ ./getinfo  -o=./tmp  --commit-list /media/B/tsp/git/linux/patches/test --git /media/B/tsp/git/linux/ -j 1
Patches: 3
starting 7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f
starting minus results
meta: parse error:
  File "parse_changes.cocci", line 379, column 32, charpos = 10837
  around = 'add_function',
  whole content = identifier f : script:ocaml() { add_function f };

cmd spatch.opt --debug parse_changes.cocci --very-quiet --include-headers-for-types --no-loops --timeout 360 -D data=/tmp/collect_diff -D tag=- -D commit=7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f -D thefile=/tmp/tmp/before_0.c /tmp/tmp/before_0.c
results: 0
spatch time: 0.03
Succeeded 0
starting plus results
starting 7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f
starting minus results
meta: parse error:
  File "parse_changes.cocci", line 379, column 32, charpos = 10837
  around = 'add_function',
  whole content = identifier f : script:ocaml() { add_function f };

cmd spatch.opt --debug parse_changes.cocci --very-quiet --include-headers-for-types --no-loops --timeout 360 -D data=/tmp/collect_diff -D tag=- -D commit=7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f -D thefile=/tmp/tmp/before_0.c /tmp/tmp/before_0.c
results: 0
spatch time: 0.03
Succeeded 0
starting plus results
starting 7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f
starting minus results
meta: parse error:
  File "parse_changes.cocci", line 379, column 32, charpos = 10837
  around = 'add_function',
  whole content = identifier f : script:ocaml() { add_function f };

cmd spatch.opt --debug parse_changes.cocci --very-quiet --include-headers-for-types --no-loops --timeout 360 -D data=/tmp/collect_diff -D tag=- -D commit=7ce6c65b617e64d310fcf18b35e29fd4d28b9c4f -D thefile=/tmp/tmp/before_0.c /tmp/tmp/before_0.c
results: 0
spatch time: 0.03
Succeeded 0
starting plus results
after parfold
after word processing 0
after parmap
done with step 3: 0
done with step 4: 0

**Comment by JuliaLawall** [comment]
Thanks for trying PatchNet.  What version of Coccinelle are you using?
Does your config.log file contain enable_ocaml='yes'?

julia

**Comment by taskset** [comment]
Hi  @JuliaLawall ,  thank you very much.
Our operating system is fedora28,
and ocaml related software is as follows:
$ opam list
...
base-bigarray base
base-threads  base
base-unix     base
conf-m4       1           Virtual package relying on m4
ocaml         4.06.0      The OCaml compiler (virtual package)
ocaml-config  1           OCaml Switch Configuration
ocaml-system  4.06.0      The OCaml compiler (system version, from outside of opam)
ocamlbuild    0.12.0      OCamlbuild is a build system with builtin rules to easily build most OCaml projects.
ocamlfind     1.8.0       A library manager for OCaml

then we manually build parmap.1.0-rc10 with reference to https://github.com/rdicosmo/parmap/issues/78,
Finally, we manually compiled coccinelle-1.0.7.

This time, preprocessing works fine.
Regards,

**Comment by JuliaLawall** [comment]
On Sun, 4 Nov 2018, Wen Yang wrote:

>
> Hi @JuliaLawall , thank you very much.
> Our operating system is fedora28,
> and ocaml related software is as follows:
> $ opam list
> ...
> base-bigarray base
> base-threads base
> base-unix base
> conf-m4 1 Virtual package relying on m4
> ocaml 4.06.0 The OCaml compiler (virtual package)
> ocaml-config 1 OCaml Switch Configuration
> ocaml-system 4.06.0 The OCaml compiler (system version, from outside of
> opam)
> ocamlbuild 0.12.0 OCamlbuild is a build system with builtin rules to easily
> build most OCaml projects.
> ocamlfind 1.8.0 A library manager for OCaml
>
> then we manually compiled parmap.1.0-rc10 with reference to
> rdicosmo/parmap#78,
> Finally, we manually compiled coccinelle-1.0.7.
>
> This time, preprocessing works fine.

Great :)  Thanks for the feedback.

julia
