### ISSUE TITLE
Blank .out files

### ISSUE THREAD

**Issue by iamkeyur** [hvdthong/PatchNetTool#4]
Hello,

When I try to run on preprocessing step on sample test data, I get blank .out and .tmp files.

[keyur@keyur-pc preprocessing]$ ./getinfo --commit-list testdata --git /home/keyur/linux -o tt -j 8
Patches: 7
after parfold
after word processing 0
after parmap
done with step 3: 0
done with step 4: 0

**Comment by JuliaLawall** [comment]
On Fri, 28 Jun 2019, Keyur wrote:

>
> Hello,
>
> When I try to run on preprocessing step on sample test data, I get blank
> .out and .tmp files.
>
> [keyur@keyur-pc preprocessing]$ ./getinfo --commit-list testdata --git
> /home/keyur/linux -o tt -j 8
> Patches: 7
> after parfold
> after word processing 0
> after parmap
> done with step 3: 0
> done with step 4: 0

Could you send me an email, as I find the github interface tiresome...

julia.lawall@lip6.fr

**Comment by iamkeyur** [comment]
I think I figured it out. My machine has problem with parmap. So, it's able run with 1 core.

**Comment by JuliaLawall** [comment]
On Fri, 28 Jun 2019, Keyur wrote:

>
> I think I figured it out. My machine has problem with parmap. So, it's able run with 1 core.

OK good.  That is what I suspected.  What is your environment? (Linux?
Windows? Mac?).

julia

**Comment by iamkeyur** [comment]
I'm running Arch Linux. I'm trying to train classifier that can differenciate commits that are fixing issues with log statements. For, example formatting printk calls or replace prink with more generic logging functions.

**Comment by JuliaLawall** [comment]
On Fri, 28 Jun 2019, Keyur wrote:

>
> I'm running Arch Linux. I'm trying to train classifier that can
> differenciate commits that are fixing issues with log statements. For,
> example formatting printk calls or replace prink with more generic logging
> functions.

OK, I'm surprised that parmap was not working on Linux, but I haven't
tried Arch Linux specifically.

julia
